baseURL: /
languageCode: en-us
title: RAR Home Inspections
theme: rar-hugo

markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
  favicon: /logo/RAR-HI_LOGO_SQUARE.svg
  brandlogo_dark: /logo/RAR-HI_LOGO_LONG.svg
  description: RAR Home Inspections - Rosenberg, TX

  
menu:
    nav:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: schedule
      name: Schedule
      url: /schedule/
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4